export const jobBoards = [
    { label: 'همه', value: 'All', id: -1 },
    { label: 'جابینجا', value: 'Jobinja', id: 0 },
    { label: 'جاب ویژن', value: 'Jobvision', id: 1 },
    { label: 'کاربوم', value: 'Karboom', id: 2 },
    { label: 'ای استخدام', value: 'EEstekhdam', id: 3 },
    { label: 'ایران تلنت', value: 'Irantalent', id: 4 },
    { label: 'دیوار', value: 'Divar', id: 5 },
    { label: 'شیپور', value: 'Sheypoor', id: 6 },
    { label: 'ایران استخدام', value: 'IranEstekhdam', id: 7 },
    { label: 'کوئرا', value: 'Quera', id: 8 },
    { label: 'میز کار', value: 'Mizehkar', id: 9 },
    { label: 'راهنما(نیازمندی های همشهری)', value: 'Rahnama', id: 10 },
    { label: 'وب سایت', value: 'webSite', id: 11 },
    { label: 'کاریابی های حضوری', value: 'Mcls', id: 12 },
    { label: 'دانشکار', value: 'Daneshkar', id: 13 },
    { label: 'همکارشو', value: 'Hamkarshow', id: 14 },
    { label: 'تلنت کوچ', value: 'Talentcoach', id: 15 },
    { label: 'بانی کار', value: 'Banikar', id: 16 },
  ];
