export const provinces = [
  { label: 'همه', id: 0 },
  { label: 'آذربایجان شرقی', id: 1 },
  { label: 'آذربایجان غربی', id: 2 },
  { label: 'اردبیل', id: 3 },
  { label: 'اصفهان', id: 4 },
  { label: 'البرز', id: 5 },
  { label: 'ایلام', id: 6 },
  { label: 'بوشهر', id: 7 },
  { label: 'تهران', id: 8 },
  { label: 'چهارمحال و بختیاری', id: 9 },
  { label: 'خراسان جنوبی', id: 10 },
  { label: 'خراسان رضوی', id: 11 },
  { label: 'خراسان شمالی', id: 12 },
  { label: 'خوزستان', id: 13 },
  { label: 'زنجان', id: 14 },
  { label: 'سمنان', id: 15 },
  { label: 'سیستان و بلوچستان', id: 16 },
  { label: 'فارس', id: 17 },
  { label: 'قزوین', id: 18 },
  { label: 'قم', id: 19 },
  { label: 'کردستان', id: 20 },
  { label: 'کرمان', id: 21 },
  { label: 'کرمانشاه', id: 22 },
  { label: 'کهگیلویه و بویراحمد', id: 23 },
  { label: 'گلستان', id: 24 },
  { label: 'گیلان', id: 25 },
  { label: 'لرستان', id: 26 },
  { label: 'مازندران', id: 27 },
  { label: 'مرکزی', id: 28 },
  { label: 'هرمزگان', id: 29 },
  { label: 'همدان', id: 30 },
  { label: 'یزد', id: 31 },
];
